services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openEarth
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 5

  spring-app:
    build: .
    container_name: app_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/openEarth
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_ADDRESS: 0.0.0.0
    ports:
      - "443:80"
    volumes:
      - ./src/main/resources/static:/app/static
      - ./keystore.p12:/app/keystore.p12
    networks:
      - app-net
    depends_on:
      mysql:
        condition: service_healthy



volumes:
  mysql_data:

networks:
  app-net: