services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openEarth
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/openearth.sql:/docker-entrypoint-initdb.d/openearth.sql
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 5

  spring-app:
    build: .
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/openEarth
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_ADDRESS: 0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/static/pictures:/app/static/pictures
      - ./keystore.p12:/app/keystore.p12
    networks:
      - app-net
    depends_on:
      mysql:
        condition: service_healthy

  angular-frontend:
    build:
      context: ../OpenEarth_Frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-net
    depends_on:
      - spring-app



volumes:
  mysql_data:

networks:
  app-net: